apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
        release: master
    spec:
      containers:
      # modify the following line with your Docker Hub account name
      # - image: index.docker.io/anthonyvetter/spring-petclinic:latest
      # - image: rifata/spring-petclinic:latest
      - image: 235975543772.dkr.ecr.us-east-2.amazonaws.com/spring-petclinic:latest
        name: spring-petclinic
        ports:
        - containerPort: 8080
